<a href="https://colab.research.google.com/github/Ibrahim341998/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# To install this library in cmd or apple cmd
# pip install numpy

In [2]:
# To import this library
import numpy as np

# How to create numpy array
arr_1d = np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [3]:
# To determine the type of arr_1d
type(arr_1d)

numpy.ndarray

In [4]:
# To find the dimensionality of the array
arr_1d.ndim

1

In [5]:
# To create the 2D array or List
arr_2d = np.array([[1,2,3],
          [1,2,3],
          [1,2,3]])
print(arr_2d)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [6]:
arr_2d.ndim

2

In [7]:
arr_1d.size

3

In [8]:
arr_2d.size

9

In [9]:
# To determine the rows and column in array
arr_2d.shape

(3, 3)

In [10]:
# To determine the data type of array
arr_2d.dtype

dtype('int64')

In [11]:
# To create 1s matrix in an array
max_1s = np.array([[1,1,1], [1,1,1], [1,1,1]])
print(max_1s)
# So for small case this fine but in long term it will not work. so we have ones function.

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
max_1s = np.ones(5)
print(max_1s)

[1. 1. 1. 1. 1.]


In [13]:
max_1s.dtype

dtype('float64')

In [14]:
# This was for having single row and multiple column. so we need todo for multiple row and multiple column.
mx_1s = np.ones((3, 4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
# To change the datatype of the matrix
mx_1s = np.ones((3,4), dtype=int)
print(mx_1s) 

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
# Similarily goes for zeros
mx_zeroes = np.zeros((4,6), dtype=int)
print(mx_zeroes)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [17]:
# we can convert our datatype to boolean as well
mx_zeroes = np.zeros((4,6), dtype=bool)
print(mx_zeroes)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [18]:
mx_0s = np.zeros((4,6), dtype=str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [19]:
em_mx = np.empty((3,3))
print(em_mx)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


# NumPy Functions

In [20]:
# import numpy as np

# arange()

In [21]:
# np.arange(start, End, steps)
ar_1d = np.arange(1, 13)
# for even arange
even_ar = np.arange(1, 13, 2)
print("ar_1d = ",ar_1d)
print("even_ar = ",even_ar)

ar_1d =  [ 1  2  3  4  5  6  7  8  9 10 11 12]
even_ar =  [ 1  3  5  7  9 11]


# linspace()


In [22]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [23]:
# to convert 1d array to 2d array
ar_2d = ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
# to convert 1d array to 3d array
ar_3d = ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel()

In [24]:
# Converts multidimensional array to 1d array
